### ISSUE TITLE
Blank space on posts.

### ISSUE THREAD

**Issue by ougijun** [themefisher/northendlab-hugo#1]
Hello, thanks for the beautiful theme.
I have question about the theme, how to fill or remove the blank space on posts? I attached the screenshot below.

**Comment by ougijun** [comment]
![IMG_20191210_114534](https://user-images.githubusercontent.com/57899491/70518019-2c304400-1b6c-11ea-8d60-c2940c18b76a.jpg)

**Comment by Somrat37** [comment]
Hey @ougijun ,
this space is for disqus, please insert a valid disqus short name.

**Comment by ougijun** [comment]
Yes, thank you for the fix.

**Comment by chriswiesner** [comment]
I still see this blank space in the latest version. no disqus name provided.
