### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by drriteshk** [themefisher/northendlab-hugo#10]
how to submit sitemap.xml and robots.txt files in this theme?

**Comment by developer-evan** [comment]
hey there, hugo is automatically generated sitemap.xml file, and for robot.txt you should follow these docs https://gohugo.io/templates/robots/

**Comment by mehedi-sharif** [comment]
Hey @drriteshk 
We are going to close this issue for this time being . If your problem is not solved please reopen here
Thanks
