### ISSUE TITLE
Searching result title js code little improvement.

### ISSUE THREAD

**Issue by stevechenzy** [themefisher/northendlab-hugo#3]
I like it very much, while implementing my own site, I found the return of search string has minor issue with Chinese and "+" sign cannot be fully replaced. here is my suggested improvement. 
layout/_default/search/list.html.

var str = (window.location.search).substr(3);
              var result = decodeURI(str.replace(/\+/g, " "));
              document.write(result);

**Comment by themefisherDev** [comment]
Thanks for your concern. i'll improve this.
