### ISSUE TITLE
adding pages

### ISSUE THREAD

**Issue by drriteshk** [themefisher/northendlab-hugo#7]
hello.
can i add pages(like: about us etc) or menu to this template by connecting my site with forestry??

**Comment by developer-evan** [comment]
Actually you can't add this type of page from forestry. you need to edit the source code.  you can follow this guide to do that https://docs.gethugothemes.com/guide/#maintain-page

**Comment by developer-evan** [comment]
I am going to close this issue. if you have more queries, don't hesitate to reopen this issue.
