### ISSUE TITLE
Changing button type in tools page

### ISSUE THREAD

**Issue by pshwetank** [themefisher/northendlab-hugo#8]
Hi, I was trying to change the button type on tools page in template with bootstrap icons but it was not displaying them correctly. Is there anything I am missing while trying to add bootstrap button in this template.

**Comment by developer-evan** [comment]
hey there, i didn't get it. Can you be little more specific? or add a screenshot or screen record. thanks

**Comment by mehedi-sharif** [comment]
Hey @pshwetank 
We are going to close this issue for this time being . If your problem is not solved please reopen here 
Thanks
